##THIS SCRIPT PUTS A RUNNING AND INTERNET ACCESSIBLE CREATE-REACT-APP TEST APP ON PORT 3000
##
##THIS IS INTENDED FOR ORACLE LINUX 7 IMAGES ON A FRESH INSTALL; ORACLE LINUX 8 HAS A DIFFERENT SCRIPT
##UPON SSH-ING INTO A CLOUD INSTANCE, THIS SCRIPT WILL INSTALL ALL THE DEPENDENCIES OF CREATE-REACT-APP AND RUN IT ON PORT 3000)
##
##IF YOU'D LIKE TO SEE THIS INSTANCE ON THE INTERNET, SIMPLY GO TO YOUR INSTANCE'S SUBNET 
##CREATE AN INGRESS RULE ALLOWING ALL TRAFFIC FROM 0.0.0.0/0 TO REACH PORT 3000
##PUNCH IN THE INSTANCE PUBLIC IP:3000 ex: 111.111.111.111:3000 INTO YOUR WEB BROWSER AND YOU'LL SEE YOUR REACT-APP

sudo yum update -y 
sudo yum install -y oracle-nodejs-release-el7 oracle-release-el7 
sudo yum install -y nodejs 
sudo npm install -y create-react-app 
npx create-react-app test 
cd test 
sudo firewall-cmd --permanent --add-port=3000/tcp
sudo firewall-cmd --reload
sudo npm start
